#!/bin/bash
set -e

CONFIG_DIR=${HOME}/Library/Application\ Support/Sublime\ Text\ 2/Packages/User
INSTALL_PACKAGECONTROL_TO=${HOME}/Library/Application\ Support/Sublime\ Text\ 2/Installed\ Packages

if [[ -d "${CONFIG_DIR}" ]]; then
    read -r -n 1 -p "Are you sure you want to erase your current Sublime Preferences directory? [y/N] " response
else
    response='y'
fi

if [[ "${response}" =~ ^([yY])$ ]]; then
    rm -rf "${CONFIG_DIR}"
else
    echo -e '\n\nOk, bye!\n'
    exit -1
fi

ln -s "${HOME}/.st2" "${CONFIG_DIR}"

echo -e '\n\nDownloading Package Control...'
curl -s -o "${INSTALL_PACKAGECONTROL_TO}/Package Control.sublime-package" https://packagecontrol.io/Package%20Control.sublime-package

echo -e '\n\nSetup complete\n'
